# Generated by Django 4.2.1 on 2023-06-24 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Roll', models.CharField(max_length=15)),
                ('Name', models.CharField(max_length=20)),
                ('Gender', models.CharField(max_length=1)),
                ('Cou', models.CharField(max_length=4)),
            ],
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Gid', models.IntegerField()),
                ('Roll', models.CharField(max_length=15)),
                ('Name', models.CharField(max_length=20)),
                ('Gender', models.CharField(max_length=1)),
                ('Cou', models.CharField(max_length=4)),
            ],
        ),
        migrations.CreateModel(
            name='Main',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Sno', models.IntegerField()),
                ('Roll', models.CharField(max_length=15)),
                ('Name', models.CharField(max_length=20)),
                ('Gender', models.CharField(max_length=1)),
                ('Cou', models.CharField(max_length=4)),
            ],
        ),
    ]
