# Generated by Django 4.2.1 on 2023-06-26 16:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('std', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='details',
            name='Cou',
            field=models.CharField(max_length=4, verbose_name='Cou'),
        ),
        migrations.AlterField(
            model_name='details',
            name='Gender',
            field=models.CharField(max_length=1, verbose_name='Gender'),
        ),
        migrations.AlterField(
            model_name='details',
            name='Name',
            field=models.CharField(max_length=20, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='details',
            name='Roll',
            field=models.CharField(max_length=15, verbose_name='Roll'),
        ),
        migrations.AlterField(
            model_name='group',
            name='Cou',
            field=models.CharField(max_length=4, verbose_name='Cou'),
        ),
        migrations.AlterField(
            model_name='group',
            name='Gender',
            field=models.CharField(max_length=1, verbose_name='Gender'),
        ),
        migrations.AlterField(
            model_name='group',
            name='Gid',
            field=models.IntegerField(verbose_name='Sno'),
        ),
        migrations.AlterField(
            model_name='group',
            name='Name',
            field=models.CharField(max_length=20, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='group',
            name='Roll',
            field=models.CharField(max_length=15, verbose_name='Roll'),
        ),
        migrations.AlterField(
            model_name='main',
            name='Cou',
            field=models.CharField(max_length=4, verbose_name='Cou'),
        ),
        migrations.AlterField(
            model_name='main',
            name='Gender',
            field=models.CharField(max_length=1, verbose_name='Gender'),
        ),
        migrations.AlterField(
            model_name='main',
            name='Name',
            field=models.CharField(max_length=20, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='main',
            name='Roll',
            field=models.CharField(max_length=15, verbose_name='Roll'),
        ),
        migrations.AlterField(
            model_name='main',
            name='Sno',
            field=models.IntegerField(verbose_name='Sno'),
        ),
        migrations.CreateModel(
            name='Messeges',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField(max_length=250, verbose_name='body')),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('roll', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='std.main')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
