# Generated by Django 4.2.1 on 2023-06-29 11:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('std', '0003_alter_messeges_roll'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='messeges',
            name='roll',
        ),
    ]
