# Generated by Django 4.2.2 on 2023-07-04 12:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('std', '0005_aiml_details_cs_details_ds_details'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ds_details',
            new_name='aiml',
        ),
        migrations.RenameModel(
            old_name='aiml_details',
            new_name='cs',
        ),
        migrations.RenameModel(
            old_name='cs_details',
            new_name='ds',
        ),
    ]
