# Generated by Django 4.2.2 on 2023-07-04 13:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('std', '0006_rename_ds_details_aiml_rename_aiml_details_cs_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='aiml',
            new_name='aiml_data',
        ),
        migrations.RenameModel(
            old_name='ds',
            new_name='cs_data',
        ),
        migrations.RenameModel(
            old_name='cs',
            new_name='ds_data',
        ),
    ]
