# Generated by Django 4.2.2 on 2023-07-04 13:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('std', '0007_rename_aiml_aiml_data_rename_ds_cs_data_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='aiml_data',
        ),
    ]
