# Generated by Django 4.2.2 on 2023-07-04 13:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('std', '0008_delete_aiml_data'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Messeges',
        ),
    ]
